### ISSUE TITLE
Fails with "Error: ENOENT: no such file or directory"

### ISSUE THREAD

**Issue by jotunskij** [auth0/repo-supervisor#11]
1. Cloned repo
2. Ran `docker build -t repo-supervisor .`
3. Ran `docker run -it --rm -v /Users/tinglev/Repos/cellus/env:/opt/scan_me repo-supervisor /bin/bash -c "source ~/.bashrc && JSON_OUTPUT=1 node /opt/repo-supervisor/dist/cli.js /opt/scan_me"`
4. Get error:
```bash
fs.js:968
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat '/opt/scan_me/.Python'
    at Object.fs.statSync (fs.js:968:11)
    at /opt/repo-supervisor/dist/cli.js:1:7631
    at Array.forEach (native)
    at e (/opt/repo-supervisor/dist/cli.js:1:7585)
    at Object.<anonymous> (/opt/repo-supervisor/dist/cli.js:1:7693)
    at t (/opt/repo-supervisor/dist/cli.js:1:177)
    at /opt/repo-supervisor/dist/cli.js:1:560
    at Object.<anonymous> (/opt/repo-supervisor/dist/cli.js:1:570)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

Output of `ls -al` for the failing file directory (which is the env-directory of a python 2.X application) is:
```bash
total 16
drwxr-xr-x   7 tinglev  staff   238 Sep  8 10:48 .
drwxr-xr-x  30 tinglev  staff  1020 Sep 12 08:26 ..
lrwxr-xr-x   1 tinglev  staff    56 Sep  8 10:48 .Python -> /Library/Frameworks/Python.framework/Versions/2.7/Python
drwxr-xr-x  39 tinglev  staff  1326 Sep  8 10:48 bin
drwxr-xr-x   3 tinglev  staff   102 Sep  8 09:07 include
drwxr-xr-x   3 tinglev  staff   102 Sep  8 09:07 lib
-rw-r--r--   1 tinglev  staff    60 Sep  8 09:07 pip-selfcheck.json
```
Let me know if you need more info!

**Comment by radekk** [comment]
It may be related to the previously closed issues I wasn't able to reproduce (#8). It was crashing on the presence of a symlink.

I've added that issue to be fixed in the next milestone. Thank you for the report.
