### ISSUE TITLE
Failing at CLI Script

### ISSUE THREAD

**Issue by bryanCoteChang** [auth0/repo-supervisor#12]
Hi!  Thank you for releasing this!  Seems very useful!

I've been trying to run it locally but have been getting this error:
```
> repo-supervisor@1.1.3 cli <DIR>
> node dist/cli.js <DIR>

Not detected any secrets in files.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! repo-supervisor@1.1.3 cli: `node dist/cli.js <DIR>`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the repo-supervisor@1.1.3 cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<USER>/.npm/_logs/2017-09-12T22_57_40_986Z-debug.log
```

Prior to running the CLI I did the install and build successfully.  Here is the log that it mentioned:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'cli',
1 verbose cli   '<DIR>' ]
2 info using npm@5.3.0
3 info using node@v6.9.5
4 verbose run-script [ 'precli', 'cli', 'postcli' ]
5 info lifecycle repo-supervisor@1.1.3~precli: repo-supervisor@1.1.3
6 info lifecycle repo-supervisor@1.1.3~cli: repo-supervisor@1.1.3
7 verbose lifecycle repo-supervisor@1.1.3~cli: unsafe-perm in lifecycle true
8 verbose lifecycle repo-supervisor@1.1.3~cli: PATH: <DIR>
9 verbose lifecycle repo-supervisor@1.1.3~cli: CWD: <DIR>/repo-supervisor
10 silly lifecycle repo-supervisor@1.1.3~cli: Args: [ '-c',
10 silly lifecycle   'node dist/cli.js "<DIR>"' ]
11 silly lifecycle repo-supervisor@1.1.3~cli: Returned: code: 1  signal: null
12 info lifecycle repo-supervisor@1.1.3~cli: Failed to exec cli script
13 verbose stack Error: repo-supervisor@1.1.3 cli: `node dist/cli.js "<DIR>"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid repo-supervisor@1.1.3
15 verbose cwd <DIR>/repo-supervisor
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "cli" "<DIR>"
```

**Comment by radekk** [comment]
It may be related to that one: https://github.com/auth0/repo-supervisor/pull/5

It's on my list, thanks for reporting.

**Comment by radekk** [comment]
It should be fixed as for now in the master branch.
