### ISSUE TITLE
Crashes with "Cannot convert object to primitive value"

### ISSUE THREAD

**Issue by glenjamin** [auth0/repo-supervisor#7]
To try this out I downloaded the repo and installed it, then tried to run it on this project's root directory. I got a crash with the following:

```
> npm version
{ 'repo-supervisor': '1.1.2',
  npm: '5.0.4',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  node: '8.1.3',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.12.0',
  v8: '5.8.283.41',
  zlib: '1.2.11' }

> node dist/cli.js .
/Users/glen/Development/GitHub/repo-supervisor/node_modules/lodash/lodash.js:13199
      result[value] = key;
                    ^

TypeError: Cannot convert object to primitive value
    at /Users/glen/Development/GitHub/repo-supervisor/node_modules/lodash/lodash.js:13199:21
    at /Users/glen/Development/GitHub/repo-supervisor/node_modules/lodash/lodash.js:3209:9
    at /Users/glen/Development/GitHub/repo-supervisor/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/glen/Development/GitHub/repo-supervisor/node_modules/lodash/lodash.js:3001:24)
    at baseInverter (/Users/glen/Development/GitHub/repo-supervisor/node_modules/lodash/lodash.js:3208:7)
    at /Users/glen/Development/GitHub/repo-supervisor/node_modules/lodash/lodash.js:5247:16
    at e.exports (/Users/glen/Development/GitHub/repo-supervisor/dist/cli.js:1:3646)
    at /Users/glen/Development/GitHub/repo-supervisor/dist/cli.js:1:2281
    at Array.forEach (native)
    at Object.processFile (/Users/glen/Development/GitHub/repo-supervisor/dist/cli.js:1:2148)
```

**Comment by radekk** [comment]
I tried to reproduce this issue successfully. It does trigger an error when you scan the current directory of repo-supervisor project.

It's caused by `node_modules/globals/globals.json` file which is a standard JSON file but it breaks `invert()` function from `lodash` module. I already filled an issue for mentioned library, depending on that I will decide what to do further.

Reported issue: https://github.com/lodash/lodash/issues/3260
